const data = {
    notes:[
        {
            id:1,
            title:'note name 1',
            description:'some description 1',
            image:'/images/silent_hill.jpg',
            countOfMembers: 5,
            geolocation: 'geo of the meeting',
            meetingDateTime: '2021-11-22 10:04:22',
            status: 1,
            money: 0,
            ageFrom: 10,
            ageTo: 15,
            rating: 4.5,
            numReviews: 8,
            gender: 'male',
            category:'sport',
            subcategory: 'volleyball'
        },
        {
            id:2,
            title:'note name 2',
            description:'some description 2',
            image:'/images/silent_hill.jpg',
            countOfMembers: 5,
            geolocation: 'geo of the meeting',
            meetingDateTime: '2021-11-22 10:04:22',
            status: 1,
            money: 0,
            ageFrom: 20,
            ageTo: 40,
            rating: 2,
            numReviews: 5,
            gender: 'male',
            category:'sport',
            subcategory: 'karate'
        },
        {
            id:3,
            title:'note name 3',
            description:'some description 3',
            image:'/images/silent_hill.jpg',
            countOfMembers: 2,
            geolocation: 'geo of the meeting',
            meetingDateTime: '2021-11-22 10:04:22',
            status: 1,
            money: 0,
            ageFrom: 10,
            ageTo: 15,
            rating: 4.5,
            numReviews: 4,
            gender: 'both',
            category:'sport',
            subcategory: 'badminton'
        },
        {
            id:4,
            title:'note name 4',
            description:'some description 4',
            image:'/images/silent_hill.jpg',
            countOfMembers: 5,
            geolocation: 'geo of the meeting',
            meetingDateTime: '2021-11-22 10:04:22',
            status: 1,
            money: 0,
            ageFrom: 10,
            ageTo: 15,
            rating: 4.5,
            numReviews: 3,
            gender: 'female',
            category:'sport',
            subcategory: 'hockey'
        },
        {
            id:5,
            title:'note name 5',
            description:'some description 5',
            image:'/images/silent_hill.jpg',
            countOfMembers: 5,
            geolocation: 'geo of the meeting',
            meetingDateTime: '2021-11-22 10:04:22',
            status: 1,
            money: 0,
            ageFrom: 10,
            ageTo: 15,
            rating: 2.5,
            numReviews: 9,
            gender: 'male',
            category:'sport',
            subcategory: 'football'
        }
    ]
}

module.exports = data;