export const NOTE_LIST_REQUEST = 'NOTE_LIST_REQUEST';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST';
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_SUCCESS';
export const NOTE_DETAILS_FAIL = 'NOTE_DETAILS_FAIL';

export const USERNOTE_LIST_REQUEST = 'USERNOTE_LIST_REQUEST';
export const USERNOTE_LIST_SUCCESS = 'USERNOTE_LIST_SUCCESS';
export const USERNOTE_LIST_FAIL = 'USERNOTE_LIST_FAIL';

export const USER_RESPONDS_REQUEST = 'USER_RESPONDS_REQUEST';
export const USER_RESPONDS_SUCCESS = 'USER_RESPONDS_SUCCESS';
export const USER_RESPONDS_FAIL = 'USER_RESPONDS_FAIL';

export const NOTE_ADD_REQUEST = 'NOTE_ADD_REQUEST';
export const NOTE_ADD_SUCCESS = 'NOTE_ADD_SUCCESS';
export const NOTE_ADD_FAIL = 'NOTE_ADD_FAIL';