export const NOTE_LIST_REQUEST = 'NOTE_LIST_REQUEST';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST';
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_SUCCESS';
export const NOTE_DETAILS_FAIL = 'NOTE_DETAILS_FAIL';

export const USERNOTE_LIST_REQUEST = 'USERNOTE_LIST_REQUEST';
export const USERNOTE_LIST_SUCCESS = 'USERNOTE_LIST_SUCCESS';
export const USERNOTE_LIST_FAIL = 'USERNOTE_LIST_FAIL';